version: '3'

services:
  db:
    image: postgres
    container_name: pgdb
    networks:
      - db-network
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pgdb

  nginx:
    container_name: ytlive-nginx
    build: 
      context: ./nginx/
      dockerfile: Dockerfile
    networks:
      - nginx-network
    restart: on-failure
    volumes:
      - ./build:/var/www/ytlive/html


  client:
    container_name: client
    build: 
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./build/:/client/dist/

  app:
    restart: on-failure
    build: ./app
    networks:
      - db-network
    ports: 
      - "3322:3322"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: pgdb
      POSTGRES_HOST: db


networks:
  db-network:
  nginx-network:
    name: nginx-network
    external: true